-- Leave Management System
-- Created by Mohammed Al Asmar

-- Table 1: Employees
CREATE TABLE LMS_EMPLOYEES (
  EMP_ID     NUMBER PRIMARY KEY,
  EMP_NAME   VARCHAR2(100),
  DEPARTMENT VARCHAR2(50),
  EMAIL      VARCHAR2(100)
);

-- Table 2: Leave Requests
CREATE TABLE LMS_LEAVES (
  LEAVE_ID   NUMBER PRIMARY KEY,
  EMP_ID     NUMBER,
  LEAVE_TYPE VARCHAR2(50),
  START_DATE DATE,
  END_DATE   DATE,
  STATUS     VARCHAR2(20) DEFAULT 'PENDING',
  REASON     VARCHAR2(500)
);
